import LocalizedStrings from 'react-native-localization';

const i18n = new LocalizedStrings({
  ru: {
    already_scanned: 'Уже просканирован',
    are_you_sure_you_want_to_exit: 'Вы уверены, что хотите выйти?',
    cancel: 'Отмена',
    client: 'Клиент',
    continue: 'Продолжить',
    event_name: 'Событие',
    in: 'Вход',
    invalid: 'Невалиден',
    login: 'Войти',
    logout: 'Выйти',
    name: 'Имя',
    no_connection: 'Нет соединения',
    out: 'Выход',
    password: 'Пароль',
    phone: 'Телефон',
    scan_history: 'История сканирований',
    start_scan: 'Начать сканирование',
    ticket_info: 'Билет',
    ticket_number: 'Номер билета',
    tickets_sold: 'Билетов продано',
    valid: 'Валиден',
    validated: 'Валидировано',
    yes: 'Да',
  },
  ro: {
    already_scanned: 'Deja scanat',
    are_you_sure_you_want_to_exit: 'Ești sigur că vrei să ieși?',
    cancel: 'Anulare',
    client: 'Client',
    continue: 'Continuare',
    event_name: 'Numele evenimentului',
    in: 'În',
    invalid: 'Nu este valid',
    login: 'Autentificare',
    logout: 'Ieșire',
    name: 'Nume',
    no_connection: 'Fără conexiune',
    out: 'Ieșire',
    password: 'Parolă',
    phone: 'Telefon',
    scan_history: 'Istoric scanare',
    start_scan: 'Începe scanarea',
    ticket_info: 'Informații despre bilet',
    ticket_number: 'Numărul biletului',
    tickets_sold: 'Bilete vândute',
    valid: 'Valid',
    validated: 'Validat',
    yes: 'Da',
  },
});

export default i18n;
